### PR TITLE
Create package structure

### PR DESCRIPTION
**Pull request by sebastiendesignolle**
Nice work! In order to facilitate its use, I've turned its structure into one of a julia package. This simplifies the installation and makes the dependencies more reliable on the long run.

- I've exported `isidentity` and `comm` for the unit tests to pass.
- I've deleted `radau.jl` which did not seem to be used anywhere.
- I'd recommend (following Mateus Araújo's advice) converting all `using` into `import` in the source files (then explicitly adding the origin of concerned functions).

Do you consider registering this package?

### CODE REVIEW

**Comment by araujoms** [comment]
I second this pull request, it would be great to have a Julia implementation of NPA that we could use in our package [Ket](https://github.com/araujoms/Ket.jl). Currently we're using [Moment](https://github.com/ajpgarner/moment) through a MATLAB interface, but the interface sucks and we don't want to have MATLAB as a dependency.

**Comment by sebastiendesignolle** [comment]
I've just run a quick benchmark to compare this with Moment (see the [paper](https://arxiv.org/abs/2406.15559) Table I page 40), and it has a less favourable scaling, but performs well versus QETLAB. Note I'm using a bigger machine than the one used by Mateus.

```julia
julia> using MosekTools

julia> @dichotomic A1 A2 B1 B2;

julia> S = A1*(B1 + B2) + A2*(B1 - B2)
A1 B1 + A1 B2 + A2 B1 - A2 B2

julia> for level in 1:16
           println("Level $level:")
           @time npa_max(S, level; solver=Mosek.Optimizer)
       end
Level 1:
  0.006962 seconds (7.98 k allocations: 392.609 KiB)
Level 2:
  0.158248 seconds (55.68 k allocations: 3.518 MiB, 90.68% gc time)
Level 3:
  0.034337 seconds (319.41 k allocations: 21.779 MiB)
Level 4:
  0.191533 seconds (1.28 M allocations: 90.360 MiB, 42.25% gc time)
Level 5:
  0.323694 seconds (3.99 M allocations: 288.101 MiB, 10.27% gc time)
Level 6:
  0.826776 seconds (10.47 M allocations: 763.520 MiB, 11.72% gc time)
Level 7:
  1.844677 seconds (24.03 M allocations: 1.730 GiB, 11.66% gc time)
Level 8:
  3.760638 seconds (49.94 M allocations: 3.623 GiB, 10.99% gc time)
Level 9:
  7.889025 seconds (95.96 M allocations: 6.994 GiB, 16.42% gc time)
Level 10:
 15.715863 seconds (173.04 M allocations: 12.660 GiB, 18.33% gc time)
Level 11:
 29.618898 seconds (296.17 M allocations: 21.745 GiB, 19.61% gc time)
Level 12:
 55.209870 seconds (485.14 M allocations: 35.705 GiB, 21.37% gc time)
Level 13:
 91.002786 seconds (765.52 M allocations: 56.477 GiB, 22.34% gc time)
Level 14:
150.244125 seconds (1.17 G allocations: 86.446 GiB, 25.24% gc time)
Level 15:
232.326992 seconds (1.74 G allocations: 128.652 GiB, 27.05% gc time)
Level 16:
357.846782 seconds (2.52 G allocations: 186.824 GiB, 29.46% gc time)
```

**Comment by araujoms** [comment]
It seems you are using an exponential-time algorithm. The complexity here is only polynomial, though.

**Comment by ewoodhead** [comment]
Thanks, I was meaning to properly turn this into a package at some point so I'll take a look when I have time.

Concerning efficiency in the meantime: I'm not completely happy with how the multiplication & simplification of monomials is done at the moment - it could certainly be improved - but the actual bottleneck seems to be [JuMP](https://jump.dev/). I don't really know why but it seems very slow to construct a model representing an SDP which it can then hand off to a solver. Generating the moment matrix itself is very fast by comparison. For example, `gamma = npa_moment(S, 16)` finishes in about 2.5 seconds on my laptop.

If you want to time them individually then generating the moment matrix, constructing the JuMP model, and running the solver can be split into separate steps like this:
```julia
gamma = npa_moment(S, level)
model = npa2jump(S, gamma, solver=Mosek.Optimizer)
optimize!(model)
```

**Comment by sebastiendesignolle** [comment]
Here the updated benchmark:

```julia
julia> for level in 1:16
           println("Level $level:")
           @time gamma = npa_moment(S, level)
           @time model = npa2jump(S, gamma, solver=Mosek.Optimizer)
           set_silent(model)
           @time optimize!(model)
       end
Level 1:
  0.000348 seconds (1.67 k allocations: 69.625 KiB)
  0.001845 seconds (5.62 k allocations: 279.797 KiB)
  0.001852 seconds (637 allocations: 40.734 KiB)
Level 2:
  0.001714 seconds (13.92 k allocations: 536.656 KiB)
  0.002961 seconds (40.43 k allocations: 2.896 MiB)
  0.003543 seconds (1.26 k allocations: 97.422 KiB)
Level 3:
  0.007301 seconds (63.21 k allocations: 2.266 MiB)
  0.019002 seconds (253.92 k allocations: 19.277 MiB, 22.07% gc time)
  0.006883 seconds (2.23 k allocations: 238.859 KiB)
Level 4:
  0.021544 seconds (195.34 k allocations: 6.773 MiB)
  0.068822 seconds (1.08 M allocations: 83.089 MiB, 11.29% gc time)
  0.018402 seconds (3.52 k allocations: 506.859 KiB)
Level 5:
  0.051964 seconds (484.69 k allocations: 16.283 MiB)
  0.222772 seconds (3.50 M allocations: 270.906 MiB, 12.03% gc time)
  0.039188 seconds (5.15 k allocations: 931.547 KiB)
Level 6:
  0.112920 seconds (1.04 M allocations: 33.851 MiB, 3.95% gc time)
  0.606000 seconds (9.42 M allocations: 728.333 MiB, 13.70% gc time)
  0.091422 seconds (7.16 k allocations: 1.334 MiB)
Level 7:
  0.206984 seconds (1.99 M allocations: 63.149 MiB, 2.08% gc time)
  1.428006 seconds (22.03 M allocations: 1.666 GiB, 12.45% gc time)
  0.192181 seconds (9.56 k allocations: 2.344 MiB)
Level 8:
  0.360254 seconds (3.52 M allocations: 109.251 MiB, 3.43% gc time)
  3.322463 seconds (46.41 M allocations: 3.512 GiB, 20.86% gc time)
  0.380785 seconds (12.34 k allocations: 4.417 MiB)
Level 9:
  0.577827 seconds (5.86 M allocations: 178.273 MiB, 2.50% gc time)
  6.906789 seconds (90.08 M allocations: 6.814 GiB, 22.29% gc time)
  0.764680 seconds (15.49 k allocations: 5.407 MiB, 0.31% gc time)
Level 10:
  0.913170 seconds (9.29 M allocations: 277.172 MiB, 2.73% gc time)
┌ Warning: The addition operator has been used on JuMP expressions a large number of times.
│ This warning is safe to ignore but may indicate that model generation is slower than necessary.
│ For performance reasons, you should not add expressions in a loop.
│ Instead of x += y, use add_to_expression!(x,y) to modify x in place
│ If y is a single variable, you may also use add_to_expression!(x, coef, y) for x += coef*y.
└ @ JuMP ~/.julia/packages/JuMP/7rBNn/src/operators.jl:282
 14.486083 seconds (164.28 M allocations: 12.420 GiB, 23.98% gc time, 3.25% compilation time)
  1.319635 seconds (19.10 k allocations: 6.840 MiB)
Level 11:
  1.404985 seconds (14.16 M allocations: 414.761 MiB, 2.45% gc time)
 26.504928 seconds (281.98 M allocations: 21.328 GiB, 22.39% gc time)
  2.010251 seconds (23.27 k allocations: 11.888 MiB)
Level 12:
  1.999531 seconds (20.82 M allocations: 599.803 MiB, 2.40% gc time)
 52.102599 seconds (464.29 M allocations: 35.105 GiB, 26.33% gc time)
  2.522491 seconds (27.83 k allocations: 14.376 MiB, 0.40% gc time)
Level 13:
  2.854810 seconds (29.75 M allocations: 843.954 MiB, 3.04% gc time)
 91.833580 seconds (735.73 M allocations: 55.629 GiB, 29.93% gc time)
  3.444084 seconds (32.81 k allocations: 24.127 MiB)
Level 14:
  3.881363 seconds (41.48 M allocations: 1.133 GiB, 2.60% gc time)
145.544028 seconds (1.13 G allocations: 85.286 GiB, 27.58% gc time)
  4.212249 seconds (38.22 k allocations: 28.204 MiB)
Level 15:
  5.757560 seconds (56.62 M allocations: 1.526 GiB, 10.19% gc time)
249.039923 seconds (1.68 G allocations: 127.095 GiB, 35.96% gc time)
  5.964502 seconds (44.06 k allocations: 31.803 MiB)
Level 16:
  7.228920 seconds (75.86 M allocations: 2.019 GiB, 6.59% gc time)
371.932463 seconds (2.45 G allocations: 184.761 GiB, 35.44% gc time)
  7.559254 seconds (50.33 k allocations: 43.051 MiB)
```

Have you ever tried to take into account the warning at level 10?

**Comment by ewoodhead** [comment]
Thanks! I've tried a few things that didn't really seem to help.

I'm kind of thinking to stop using JuMP based on those benchmarks; it's slow for some reason I've never understood or figured out what to do about.

An earlier version of the code was using [Convex.jl](https://jump.dev/Convex.jl/stable/). I basically switched to using JuMP at some point since it seemed more "modern" and it seemed to somehow sometimes generate SDPs that could be solved a bit more quickly, even if JuMP itself was taking some time to process the optimisation problem. But I wasn't testing on such large problems at the time.

**Comment by araujoms** [comment]
No, come on, Convex.jl is essentially abandoned. Let me try a couple of things first; if it doesn't work we should post it on the Julia discourse, the JuMP devs will certainly be willing to help.

**Comment by ewoodhead** [comment]
Okay, thanks! That would be appreciated. After doing the relaxation we have a problem that is an SDP and we essentially just want to hand it off to an SDP solver. It really doesn't seem that part of the problem should be the bottleneck...

Concerning the warning about the addition operator, it seems to come from repeated use of calling the trace function in the `sdp2jump` function in `npa_impl.jl`, specifically in this loop:
```julia
    for m in mons
        c = expr[m]
        Fs = (ineq[m] for ineq in ineqs)
        tr_term = sum(LinearAlgebra.tr(F*Z)
                      for (F, Z) in zip(Fs, Zs))
            
        @constraint(model, tr_term + s*c == 0)
    end
```
A quick change I just did to see gets rid of the warning but doesn't seem to improve the performance significantly:
```julia
    for m in mons
        c = expr[m]
        Fs = (ineq[m] for ineq in ineqs)

        tr_term = AffExpr()

        for (F, Z) in zip(Fs, Zs)
            (m, n) = size(Z)

            for i in 1:m
                for j in 1:n
                    add_to_expression!(tr_term, F[j,i]*Z[i,j])
                end
            end
        end

        add_to_expression!(tr_term, c*s)

        @constraint(model, tr_term == 0)
    end
```

JuMP's documentation also suggests [disabling bridges](https://jump.dev/JuMP.jl/stable/tutorials/getting_started/performance_tips/#Suggestion-2:-disable-bridges-if-none-are-being-used), but that a) also doesn't seem to significantly improve performance and b) prevents the code from working with the SCS solver, which it is set up to use by default since it doesn't require a license.

**Comment by araujoms** [comment]
I just changed this trace to an inner product, and got a massive increase in performance:
```julia
tr_term = sum(LinearAlgebra.dot(F,Z) for (F, Z) in zip(Fs, Zs))
```

**Comment by araujoms** [comment]
But indeed, this part of the problem should be trivial. It doesn't take any appreciable time in moment. Even with the inner product it's taking much longer than it should. Can you walk me through what your function is doing here? `mons` is a list of monomials; then you create a tuple `Fs` from for each `ineqs`, what are the `ineqs`? And then you sum their inner product over these `Zs`, which are all JuMP matrices constrained to be PSD? So you're doing the SOS version of NPA? But the `Zs` don't seem to be square, so I'm very confused.

**Comment by ewoodhead** [comment]
I'll have to go through my code this weekend to try to remember what it does, but briefly a few things:

I experimented with different formats while writing the code a year or two ago, particularly giving the solvers either the primal SDP or its dual after the relaxation. I think I settled on giving the dual.

The matrices should be square as far as I can remember, i.e., `m` and `n` should be the same numbers. I think I have this simply due to the `size` function returning both the number of rows and columns.

`ineqs` is a list of moment matrices that you want to be positive semidefinite. The first one is simply the moment matrix from the NPA relaxation (after substitutions/simplifications from equality constraints, if any). The remaining elements correspond to inequality constraints, if any (i.e., if you gave `npa_max` a `ge=` parameter). There won't be any if you're just maximising CHSH.

(I think a previous version of the code was representing `ineqs` as a single block-diagonal matrix but I was having some trouble with this.)

The moment matrix (output by, e.g., `gamma = npa_moment(S, level)`) is represented as a polynomial with sparse matrices as the coefficients, multiplied by quantum operators. You can index into it, so, e.g., `gamma[Id]` will tell you everywhere the expectation value of the identity operator appears in the moment matrix. Calling `monomials(gamma)` will list all the monomials.

**Comment by ewoodhead** [comment]
Ok, so the purpose of this `sdp2jump` function is to take an NPA relaxation and make a JuMP object representing the optimisation problem out of it.

As I mentioned I thought I'd done, `sdp2jump` actually gives JuMP the dual to the NPA relaxation. I don't remember exactly what the results were but I tried giving Convex.jl and JuMP both the primal and dual problems in the past and apparently ended up deciding to do it this way.

Explicitly, if the problem is:
```math
\begin{eqnarray}
  \text{maximise} &\quad&
    c_{\mathbb{I}} + \sum_{X \neq \mathbb{I}} c_{X} \langle X \rangle \\
  \text{subject to} &&
    F_{\mathbb{I}} + \sum_{X \neq \mathbb{I}} F_{X} \langle X \rangle \geq 0
\end{eqnarray} \,,
```
with the sums taken over all operators $X$ in the relaxation except for the identity, then the dual that `sdp2jump` gives to JuMP is
```math
\begin{eqnarray}
  \text{minimise} &\quad&
    c_{\mathbb{1}} + \mathrm{Tr} \bigl[ F_{\mathbb{I}} Z \bigr] \\
  \text{subject to} &&
    \mathrm{Tr} \bigl[ F_{X} Z \bigr] + c_{X} = 0 \,, \qquad \forall X \neq \mathbb{I} \\
  &&
    Z \geq 0
\end{eqnarray} \,.
```

With respect to the first (primal) problem:
  - the objective is given to `sdp2jump` in the `expr` parameter. It's expected to be a polynomial operator $\sum_{X} c_{X} X$, e.g., $A_{1} B_{1} + A_{1} B_{2} + A_{2} B_{1} - A_{2} B_{2}$. `expr[Id]` gives the coefficient $c_{\mathbb{I}}$, and so on.
  - `ineqs` is an array of polynomial operators, whose coefficients can be matrices, that we want to impose are nonnegative or positive semidefinite. The first element of `ineqs` is the moment matrix of the NPA relaxation. Additional elements exist if you impose additional inequality constraints. For example, if you wanted to impose that $\langle A_{1} \rangle + \langle B_{1} \rangle \leq 0.7$ then the polynomial $0.7 \mathbb{I} - A_{1} - B_{1}$ would appear as a second element of `ineqs`.

`sdp2jump` also lets you say if you want to minimise the objective instead of maximise it (`goal` parameter) and optionally say what solver you want to use (`solver`) and how verbose you want JuMP to be (`verbose`). Minimising the objective just means we have to tell JuMP to `Max` the dual instead of `Min` it and change a couple of signs in the dual problem; this is done with the `s` variable in the function body.

The content of `sdp2jump` is then just constructing a JuMP model representing the dual problem given above.

After creating a new JuMP model, the first thing it does is create objects for JuMP representing the positive definite $`Z`$s of the dual above:
```julia
    Zs = [@variable(model, [1:m, 1:n], PSD)
          for (m, n) in size_as_pair.(ineqs)]
```
There will be one such $Z$ for each element in `ineqs`. Normally, the first will be the size of the NPA moment matrix and any additional ones will just be $1 \times 1$ matrices.

The next two expressions then get the $`F_{\mathbb{I}}`$s out of the `ineqs` and construct the objective $\mathrm{Tr} \bigl[ F_{\mathbb{I}} Z \bigr]$:
```julia
    Ids = (ineq[Id] for ineq in ineqs)
    objective = (sum(LinearAlgebra.tr(s*m*z)
                     for (m, z) in zip(Ids, Zs))
                 + expr[Id])
```
(Looking at this now I could have picked better variable names: e.g., `F_Ids`, `F_Id`, and `Z` instead of `Ids`, `m`, and `z`.)

After telling JuMP to `Min` or `Max` the objective, the next thing it does is construct the constraints of the dual problem. This line, first, makes a list of all the monomials appearing in the problem except for the identity, which we want to loop over:
```julia
    mons = collect(m for m in monomials(expr, ineqs) if !isidentity(m))
```
And this loop, where `sdp2jump` seems to be spending the vast majority of its time, is just adding the constraints to the JuMP model:
```julia
    for m in mons
        c = expr[m]
        Fs = (ineq[m] for ineq in ineqs)
        tr_term = sum(LinearAlgebra.(F*Z)
                      for (F, Z) in zip(Fs, Zs))
            
        @constraint(model, tr_term + s*c == 0)
    end
```

**Comment by araujoms** [comment]
Thanks for explaining everything. I don't think it is a good idea to uses 1x1 PSD matrices to enforce nonnegativity constraints; unless JuMP does some miracle there it should be terribly inefficient. Instead the proper way is to do something like `@variable(model, v[1:d] >= 0)`. This uses a single nonnegative cone, which should be much faster than `d` nonnegative cones, which should be much faster than `d` 1x1 PSD cones.

**Comment by ewoodhead** [comment]
Thanks, I'll take a look. I'll probably want to test first to see if it makes a practical difference.

That said, inequality constraints are really meant just to handle, e.g., if you want to put something like $\langle A_{1} B_{1} + A_{1} B_{2} + A_{2} B_{1} - A_{2} B_{2} \rangle \geq \text{some number}$ in the problem. I think the normal case is that you would have no such constraints or maybe a handful of them. I'd expect you're always better off using equality constraints if they will do since these are used to make the problem smaller: they eliminate variables in the primal and constraints in the dual.

**Comment by araujoms** [comment]
Frankly I'd change it just to make the code clearer, it's very confusing to bundle it together with the moment matrix. If you hadn't explained I would have never found out what was going on.

**Comment by ewoodhead** [comment]
Why do you find this confusing? The main purpose of the code is to convert a quantum optimisation problem to an SDP in standard form, and then hand that off to a solver. I am only using JuMP so I don't have to write code to call different solvers with slightly different formats directly or limit the code to only working with one solver.

From my point of view this means: the NPA relaxation should map inequality constraints on expectation values to $1 \times 1$ blocks, because that's what you can have in an SDP in standard form. Then, I could, in principle, write code to check for $1 \times 1$ blocks and handle them specially, if it turns out that it's more efficient that way and it makes a significant difference. But if it is, it will really be an internal/optimisation detail to do with how JuMP or some solvers work, and changing the code without measuring this first would be premature optimisation.

A second thing here: it is currently the case that the first element of `ineqs` will be an $n \times n$ moment matrix and then any remaining ones will be $1 \times 1$, but that may not always be true. Particularly, it's likely I'll want to add additional moment matrices to support operator constraints in the future. `sdp2jump` is meant to already handle being able to receive those additional matrices; I just happen not to have written code to generate them yet.

**Comment by araujoms** [comment]
I'm afraid that's a common misconception. You don't want a standard form SDP, you want a standard form conic program. A conic program can use several different cones, one of which is the PSD cone. It's not the only one, however. Also very common are the non-negative cone, which gives rise to linear programs, and the 2-norm cone, which gives rise to second order cone programs.

The cause of the confusion is that one can represent exactly the non-negative cone and the 2-norm cone as particular cases of the PSD cone. It's very inefficient, though. You should always keep the original cone when you can. And you pretty much always do, as conic solvers almost always support both the non-negative cone and the 2-norm cone directly; in any case the solvers you are using, Mosek and SCS do.

If you do add support for localizing matrices, sure, they actually need to be PSD matrices. But stuff as $\langle A_{1} \rangle \geq 0.5$ is conceptually just a non-negative constraint, and it's much better to represent it like this. I don't know if it will actually be faster, because it's likely that JuMP will silently reformulate it as a non-negative constraint. For example, I know that if you try to give a 1x1 PSD constraint to Mosek directly it gives an error, so if it works with Mosek it means JuMP is doing this.

**Comment by ewoodhead** [comment]
I'm not very convinced by this. Mathematically, at least, requiring that $x$ is nonnegative and requiring that the $1 \times 1$ matrix $[x]$ is PSD is exactly the same thing, so this is in principle giving JuMP exactly the same information. The rest seems to be a matter of how you like to look at or classify things, or what might be better for JuMP or for this or that solver. The latter is the only one here I'm really going to be concerned with.

Now, as far as `sdp2jump` is concerned, it gets a list `ineqs` of polynomials that are supposed to be nonnegative/PSD, some of which may happen to be scalar. What you're suggesting the code should do here is treat any constraints that happen to be scalar as a special case: either `sdp2jump` should get them as a separate parameter or it should test for polynomials with scalar coefficients in `ineqs` and tell JuMP that these particular constraints are scalar. Either would certainly be very easy to do and, if it's important to make this distinction for some technical/performance reason then, like I said, I'll check and, sure, I'll change if necessary. But if it's not important or if it is and JuMP is already capable of detecting it, then what for?

**Comment by araujoms** [comment]
> or what might be better for JuMP or for this or that solver. The latter is the only one here I'm really going to be concerned with.

It will certainly be better for every solver in existence to give it as non-negative constraint.

> But if it's not important or if it is and JuMP is already capable of detecting it, then what for?

I don't know if JuMP is already detecting it. Probably it is, but I think relying on it for this is bad design. It makes the code harder to understand and potentially slower.

**Comment by ewoodhead** [comment]
> It will certainly be better for every solver in existence to give it as non-negative constraint.

Including an SDP solver? This may admittedly not be so relevant any more, but the whole library did originate as a Julia version of one I'd already written in Lisp, which calls out to SDPA to do the optimisation. SDPA takes an SDP in a standard form: the only optimisation variables it understands is $n$ PSD matrices of different sizes or, equivalently, a single PSD with a given block diagonal structure.



> I don't know if JuMP is already detecting it. Probably it is, but I think relying on it for this is bad design. It makes the code harder to understand and potentially slower.

I would have a different prejudice personally: if you have an algorithm that works with problem instances of size $n$ and it handles the case $n = 1$ badly and you need to handle that specially then I would tend to think probably a better/more general algorithm exists.

There are situations where you have algorithms that work well for small $n$ and different algorithms that work better for large $n$, but having to treat specifically $n = 1$ differently from everything else seems very strange to me.

**Comment by araujoms** [comment]
Add this to the pile of reasons why SDPA is obsolete.

The algorithms for optimizing over PSD matrices and non-negative cones are just different. In the non-negative case, the cone is given by vectors $x$ such that $x_i \ge 0\ \forall i$, and the barrier function by $-\sum_i \log(x_i)$. In the PSD case, the cone is given by matrices $X$ such that $X \succeq 0$, and the barrier function by $-\mathrm{logdet}(X)$. Now the cones (and barrier functions) coincide when $x$ has a single component and $X$ is a 1x1 matrix, which means that instead of optimizing over a single $d$-dimensional non-negative cone you can optimize over $d$ 1x1 PSD cones. It's a terrible idea, though.

**Comment by ewoodhead** [comment]
> Add this to the pile of reasons why SDPA is obsolete.

Independently of any specific merits or drawbacks of SDPA, is there a reason I should rule out my code working with an SDP solver like that? For a solver like that, JuMP would have to convert any scalar constraints into $1 \times 1$ PSDs, so either I would have to start writing code specialising for different kinds of solvers (I kind of thought it was JuMP's job to be able to do that) or I'd be, in one direction or the other, relying on JuMP to recognise the equivalence between a nonnegative number and a $1 \times 1$ PSD anyway.


> It's a terrible idea, though.

Do you have evidence for this?

Otherwise I don't really see why you continue arguing here: you've already flagged this as a likely problem that I'm going to have to look into in some depth when I find the time for it.

**Comment by araujoms** [comment]
Indeed, that's JuMP's job. It supports non-negative constraints in SDPA precisely by rewriting them as 1x1 PSD constraints. I don't know if it rewrites 1x1 PSD constraints as non-negative constraints for the solvers that support them (I guess it does), or if it rewrites $d$ non-negative constraints as one $d$-dimensional non-negative constraint (I guess it doesn't). You could ask the JuMP devs, you have seen that they are responsive.

I'm not going to do any benchmarking, if that's what you are asking. It's obvious from knowing how the algorithm works. And I thought we were having a conversation here. If you're annoyed by my comments I'm sorry, I'll stop replying.

**Comment by ewoodhead** [comment]
No, it's fine. I'll likely just make the change in a few weeks if it looks like it's a real issue. There are just maybe a few things I'd like to check to do with how JuMP works first.

**Comment by ewoodhead** [comment]
> or if it rewrites $d$ non-negative constraints as one $d$-dimensional non-negative constraint (I guess it doesn't).

I don't know either but I would really hope it does: maybe it's more efficient for a solver to be given a $d$-dimensional nonnegativity constraint rather than separate scalar constraints (assuming it's even possible to give a solver these as distinct things), but I might prefer to make some of them named nonnegative variables in my code just for readability for instance.

Then, with PSDs (this is the sort of thing I may want to look into a bit), when you use JuMP to create a PSD matrix to refer to in your problem, it doesn't seem to simply make an object representing a PSD matrix. It makes what looks like a Julia array of JuMP variable objects, which I guess it is somewhere tracking behind the scenes make up the components of a PSD between them. If there's just one such variable object then, mathematically at least, the constraint reduces to this single variable just being nonnegative. I don't know what information JuMP works with internally then in that case.

**Comment by ewoodhead** [comment]
Eh, never mind with that second comment; JuMP just seems to track in the model that this single variable is in a PSD cone:
```julia
julia> model = Model();

julia> Z = @variable(model, [1:1, 1:1], PSD);

julia> model
A JuMP Model
Feasibility problem with:
Variable: 1
`Vector{VariableRef}`-in-`MathOptInterface.PositiveSemidefiniteConeTriangle`: 1 constraint
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.
```

**Pull request merged**
